### ISSUE TITLE
New image wasn't generated

### ISSUE THREAD

**Issue by LeoColman** [cyber-dojo-languages/kotlin-test#2]
Hey guys!

At #1 we updated the jars to a newer version. However, I believe a new image wasn't generated, and the old jars are still being used, and thus tests can't be executed

How can I trigger the generation of a new image?

**Comment by JonJagger** [comment]
I will look into it today.

**Comment by JonJagger** [comment]
Hi Leonardo.
Fixed now. Thank you for highlighting this was not working.
Details... There is a service called puller which pulls the latest versions of all the langauge-test-framework images from dockerhub every 24 hours as a cron job. I broke it because of a refactoring which had changed the name of some dependent services. Sorry.

**Comment by LeoColman** [comment]
Nice catch!
Thanks for the support :)
